# Generated by Django 3.2 on 2021-04-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0002_auto_20210422_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(choices=[('underweight', 'UNDERWEIGHT'), ('overweight', 'OVERWEIGHT'), ('obsessed', 'OBSESSED')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='calculator',
            name='result',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=500),
            preserve_default=False,
        ),
    ]
