# Generated by Django 3.2 on 2021-04-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0003_auto_20210422_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion',
            field=models.CharField(choices=[('underweight', 'UNDERWEIGHT'), ('normalweight', 'NORMALWEIGHT'), ('overweight', 'OVERWEIGHT'), ('obsessed', 'OBSESSED')], max_length=255),
        ),
    ]
