# Generated by Django 3.2 on 2021-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0005_suggestion_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
