# Generated by Django 3.2 on 2021-05-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0009_remove_calculator_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
