# Generated by Django 3.2 on 2021-05-21 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmiapp', '0010_delete_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculator', to=settings.AUTH_USER_MODEL),
        ),
    ]
